config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  get 'homepage/index'
  post 'solution', to: 'homepage#solution'
end

app/models/page_quiz.rb
class PageQuiz
  include ActiveModel::Model

  attr_accessor :total_digit

  def self.create_problem(range = 20..500)
    new(total_digit: rand(range))
  end

  def solution
    (self.total_digit + (10 ** digit_number/9 - digit_number))/digit_number
  end

  def digit_number
    (Math.log10(self.total_digit) + 1 ).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @problem = PageQuiz.create_problem
    session[:total_digit] = @problem.total_digit
  end

  def solution
    solution = PageQuiz.new(total_digit: session[:total_digit]).solution
    if params[:solution].to_i == solution
      render json: "Correct!"
    else
      render json: "Wrong!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/index.html.erb
<div class="inner cover">
<h1 class="cover-heading">Count Number of Page</h1>
<p class="lead">To number a book from 1 to its last page took <%= @problem.total_digit %> digits. How many pages are there in the book?</p>
<p><em>hint: Book with 9 pages took 9 digits, and Book with 10 pages took 11 digits</em></p>
<%= form_tag solution_path, class: "form-horizontal", id: "submit-answer", remote:true do %>
  <div class="form-group">
    <%= label_tag :solution, 'Solution:', class: 'col-sm-offset-3 col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= text_field_tag :solution, params[:solution], class: 'form-control' %>
    </div>
  </div>
  <p class="lead">
    <%= submit_tag 'Submit Solution', class: 'btn btn-lg btn-default' %>
  </p>
  <span id="result"></span>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geekuizz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <div class="cover-container">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>